name: _error
timestamp: 1634091368
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1634091368
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-4223: Logo
  spacer:
    spacer-3909: Spacer
    spacer-7428: Spacer
  menu:
    menu-4006: Menu
  content:
    system-content-8024: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-3513: Copyright
  branding:
    branding-3496: Branding
  mobile-menu:
    mobile-menu-2972: Mobile-menu
inherit: {  }
