version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1634091368
layout:
  /header/:
    -
      - 'logo-4223 30'
      - 'spacer-3909 70'
  /navigation/:
    -
      - menu-4006
  /main/:
    -
      - system-content-8024
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3513 40'
      - 'spacer-7428 30'
      - 'branding-3496 30'
  offcanvas:
    -
      - mobile-menu-2972
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
