name: _offline
timestamp: 1634091368
version: 7
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1634091368
positions:
  footer: Footer
sections:
  header: Header
  main: Main
  footer: Footer
particles:
  logo:
    logo-5243: Logo
  spacer:
    spacer-4584: Spacer
    spacer-3490: Spacer
  messages:
    system-messages-1162: 'System Messages'
  content:
    system-content-5294: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-6863: Copyright
  branding:
    branding-8965: Branding
inherit: {  }
