name: '13'
timestamp: 1634164105
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1634011015
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-4541: 'System Messages'
  logo:
    logo-2701: Logotipo
    logo-5653: Logotipo
  menu:
    menu-1443: Menu
    menu-9011: Menu
  social:
    social-6848: Social
  owlcarousel:
    owlcarousel-2455: 'Carrusel de búhos'
  custom:
    custom-5807: Intro
    custom-3119: Características
    custom-7658: 'Recomendaciones de clientes'
    custom-1900: 'HTML personalizado'
    custom-6355: 'Desarrolle temas de CMS rápidamente'
    custom-4864: 'HTML personalizado'
    custom-2282: 'HTML personalizado'
  contenttabs:
    contenttabs-3854: 'Fichas de contenido'
  contentcubes:
    contentcubes-7850: 'Cubos de contenido'
  spacer:
    spacer-2826: Espaciador
    spacer-7876: Espaciador
  copyright:
    copyright-8596: Copyright
  totop:
    totop-3177: 'Hasta arriba'
  mobile-menu:
    mobile-menu-4999: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-4541: system-messages-7972
    logo-2701: logo-9608
    menu-1443: menu-6409
    social-6848: social-3171
    menu-9011: menu-9700
    footer: footer
    spacer-2826: spacer-4251
    logo-5653: logo-9571
    copyright-8596: copyright-1736
    custom-4864: custom-7995
    custom-2282: custom-7238
    totop-3177: totop-8670
    spacer-7876: spacer-1685
    offcanvas: offcanvas
    mobile-menu-4999: mobile-menu-5697
