name: _body_only
timestamp: 1634091368
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1634091368
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-3662: 'System Messages'
  content:
    system-content-6409: 'Page Content'
inherit: {  }
